---
- hosts: splunk-nodes
  become: true
  tasks:

- name: Copy the splunk enterprise rpm
  get_url:
      url: https://download.splunk.com/products/splunk/releases/9.1.2/linux/splunk-9.1.2-b6b9c8185839.x86_64.rpm
      dest: /opt
      mode: '0644'

  - name: Install the splunk enterprise
    yum:
      name: /opt/splunk-9.1.2-b6b9c8185839.x86_64.rpm
      state: present

  - name: Start the splunk enterprise
    command: /opt/splunk/bin/splunk start --accept-license --answer-yes --no-prompt --seed-passwd password

  - name: Configure the splunk enterprise to start at boot time
    command: /opt/splunk/bin/splunk enable boot-start

  - name: Enable listening on Splunk Indexer
    command: /opt/splunk/bin/splunk enable listen 9997 -auth admin:password

  - name: Restart Splunk service
    command: /opt/splunk/bin/splunk restart
    register: splunk_service_status

  - debug: var=splunk_service_status

