---
- hosts: splunk-nodes
  become: true
  tasks:

  - name: Copy the splunk enterprise rpm
    copy:
          src: /root/splunk-8.0.6-152fb4b2bb96-linux-2.6-x86_64.rpm
          dest: /opt/splunk-8.0.6-152fb4b2bb96-linux-2.6-x86_64.rpm
          owner: root
          group: root
          mode: '0644'

  - name: Install the splunk enterprise
    yum:
      name: /opt/splunk-8.0.6-152fb4b2bb96-linux-2.6-x86_64.rpm
      state: present

  - name: Start the splunk enterprise
    command: /opt/splunk/bin/splunk start --accept-license --answer-yes --no-prompt --seed-passwd password

  - name: Configure the splunk enterprise to start at boot time
    command: /opt/splunk/bin/splunk enable boot-start

  - name: Enable listening on Splunk Indexer
    command: /opt/splunk/bin/splunk enable listen 9997 -auth admin:password

  - name: Restart Splunk service
    command: /opt/splunk/bin/splunk restart

